
# Required packages
require(tidyverse)

# Plot constants
tag_size <- 14
strip_size <- 12
title_size <- 10
text_size <- 8
common_theme <- theme_minimal() +
  theme(
    legend.position = "none",
    panel.border = element_rect(colour = "grey90", fill = NA, linewidth = 0.5),
    panel.grid.major = element_line(linewidth = 0.3),
    panel.grid.minor = element_line(linewidth = 0.15),
    axis.ticks = element_blank(),
    axis.text = element_text(size = text_size),
    axis.title = element_text(size = title_size),
    plot.title = element_text(face = "bold", size = title_size, hjust = 0.5),
    strip.text = element_text(face = "bold", size = strip_size),
    plot.margin = margin(1, 1, 1, 1, "pt"),
    aspect.ratio = 1
  )

# Domain boundaries: North-south latitude limits for Australia, matching
# 08_Mid-domain_null_models.R
lat_min <- 10.5
lat_max <- 44.5
domain_size <- lat_max - lat_min

# Load the data generated by 08_Mid-domain_null_models.R
load("generated_data/figure_6.RData")

# Annotate R2 values for observed models
r2_summary <- r2_combined %>%
  rowwise() %>%
  mutate(
    # Build a plot math-safe label where the number is a quoted string
    label = paste0('italic(R)^2 == \"', sprintf("%.2f", R2), '\"')
  ) %>%
  ungroup()

# Plot with the mid-domain effect (MDE) null model
figure_6 <- ggplot() +
  geom_point(data = data, aes(x = latitude, y = env_breadth),
             alpha = 0.25, size = 0.3) +
  # MDE null model
  geom_ribbon(data = mde_combined,
              aes(x = x, ymin = conf.low, ymax = conf.high),
              alpha = 0.2, fill = "#de2d26") +
  geom_line(data = mde_combined, aes(x = x, y = predicted),
            color = "#de2d26", linewidth = 0.5) +
  # Observed pattern in blue
  geom_ribbon(data = pred_combined,
              aes(x = x, ymin = conf.low, ymax = conf.high),
              alpha = 0.2, fill = "#3366FF") +
  geom_line(data = pred_combined, aes(x = x, y = predicted),
            color = "#3366FF", linewidth = 0.5) +
  # Add degrees south symbol to x-axis
  scale_x_continuous(
    labels = function(x) paste0(abs(x), "°S")
  ) +
  # Add R2 annotations
  geom_text(
    data = r2_summary,
    aes(
      x = lat_min + 0.99 * domain_size,
      y = max(data$env_breadth, na.rm = TRUE) * 0.99,
      label = label
    ),
    parse = TRUE,
    hjust = 1,
    vjust = 1,
    size = 2.5,
    colour = "black",
    inherit.aes = FALSE
  ) +
  labs(
    x = "Latitude",
    y = "Environmental breadth"
  ) +
  common_theme +
  facet_wrap(~ mycorrhizal_type, nrow = 1)

# Display the plot
print(figure_6)

# Save the plot
ggsave(
  "output/figure_6.png",
  plot = figure_6,
  width = 173,
  height = 54,
  units = "mm",
  bg = "white",
  dpi = 300
)
ggsave(
  "output/figure_6.tif",
  plot = figure_6,
  width = 173,
  height = 54,
  units = "mm",
  bg = "white"
)
ggsave(
  "output/figure_6.pdf",
  plot = figure_6,
  width = 173,
  height = 54,
  units = "mm",
  bg = "white",
  device = cairo_pdf
)
